# Travis CI settings

language: python

python:
  - '3.4'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python3 restapi/manage.py test
  - pylint restapi/api/  # Syntax validation